# Generated by Django 4.1.3 on 2026-09-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0005_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='unit_price',
            new_name='total',
        ),
    ]
